using UnityEngine;
using System.Collections;

public class blastWeapon : MonoBehaviour {
	public GameObject shot;
	public GameObject explosion;

	// Use this for initialization
	void Start () {

	
	}
	
	// Update is called once per frame
	void Update () {
		GameObject yo = GameObject.Find("Player");
		if(Input.GetKeyDown("space") && yo.GetComponent<Done_PlayerController>().shotAmount<=500){
			if (yo.GetComponent<Done_PlayerController>().powerUp==0){
				Instantiate(shot, this.transform.position, new Quaternion(0, 0,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 60,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 120,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 180,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 240,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 300,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 360,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -60,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -120,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -180,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -240,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -300,0,90));
				yo.GetComponent<Done_PlayerController>().shotAmount+=12;

				Instantiate(explosion, transform.position, transform.rotation);
				yo.GetComponent<Done_PlayerController>().onScreen=false;
				Destroy(gameObject);
			}
			if (yo.GetComponent<Done_PlayerController>().powerUp==1){
				Instantiate(shot, this.transform.position, new Quaternion(0, 0,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 40,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 80,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 120,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 160,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 200,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 240,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 280,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 320,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 360,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -40,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -80,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -120,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -160,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -200,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -240,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -280,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -320,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -360,0,90));
				yo.GetComponent<Done_PlayerController>().shotAmount+=19;
				Instantiate(explosion, transform.position, transform.rotation);
				yo.GetComponent<Done_PlayerController>().onScreen=false;
				Destroy(gameObject);
			}
			if (yo.GetComponent<Done_PlayerController>().powerUp==2){
				Instantiate(shot, this.transform.position, new Quaternion(0, 0,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 20,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 40,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 60,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 80,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 100,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 120,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 140,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 160,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 180,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 200,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 220,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 240,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 260,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 280,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 300,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 320,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 340,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 360,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -20,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -40,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -60,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -80,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -100,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -120,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -140,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -160,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -180,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -200,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -220,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -240,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -260,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -280,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -300,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -320,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -340,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -360,0,90));
				yo.GetComponent<Done_PlayerController>().shotAmount+=37;

				Instantiate(explosion, transform.position, transform.rotation);
				yo.GetComponent<Done_PlayerController>().onScreen=false;
				Destroy(gameObject);
			}
				if (yo.GetComponent<Done_PlayerController>().powerUp==3){
					Instantiate(shot, this.transform.position, new Quaternion(0, 0,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 20,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 40,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 60,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 80,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 100,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 120,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 140,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 160,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 180,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 200,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 220,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 240,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 260,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 280,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 300,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 320,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 340,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, 360,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -20,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -40,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -60,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -80,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -100,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -120,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -140,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -160,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -180,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -200,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -220,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -240,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -260,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -280,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -300,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -320,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -340,0,90));
					Instantiate(shot, this.transform.position, new Quaternion(0, -360,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 10,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 30,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 50,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 70,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 90,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 110,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 130,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 150,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 170,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 190,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 210,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 230,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 250,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 270,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 290,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 310,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 330,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 350,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, 10,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -30,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -50,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -70,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -90,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -110,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -130,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -150,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -170,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -190,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -210,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -230,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -250,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -270,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -290,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -310,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -330,0,90));
				Instantiate(shot, this.transform.position, new Quaternion(0, -350,0,90));
				yo.GetComponent<Done_PlayerController>().shotAmount+=73;
				Instantiate(explosion, transform.position, transform.rotation);
				yo.GetComponent<Done_PlayerController>().onScreen=false;
				Destroy(gameObject);
			}
		if (yo.GetComponent<Done_PlayerController>().powerUp==4){
			Instantiate(shot, this.transform.position, new Quaternion(0, 5,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 10,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 15,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 20,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 25,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 30,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 35,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 40,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 45,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 50,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 55,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 60,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 65,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 70,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 75,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 80,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 85,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 90,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 95,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 100,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 105,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 110,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 115,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 120,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 125,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 130,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 135,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 140,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 145,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 150,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 155,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 160,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 165,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 170,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 175,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 180,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 185,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 190,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 195,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 200,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 205,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 210,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 215,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 220,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 225,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 230,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 235,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 240,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 245,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 250,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 255,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 260,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 265,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 270,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 275,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 280,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 285,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 290,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 295,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 300,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 305,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 310,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 315,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 320,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 325,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 330,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 335,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 340,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 345,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 350,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 355,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, 360,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -5,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -10,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -15,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -20,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -25,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -30,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -35,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -40,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -45,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -50,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -55,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -60,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -65,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -70,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -75,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -80,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -85,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -90,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -95,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -100,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -105,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -110,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -115,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -120,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -125,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -130,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -135,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -140,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -145,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -150,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -155,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -160,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -165,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -170,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -175,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -180,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -185,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -190,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -195,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -200,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -205,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -210,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -215,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -220,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -225,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -230,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -235,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -240,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -245,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -250,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -255,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -260,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -265,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -270,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -275,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -280,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -285,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -290,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -295,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -300,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -305,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -310,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -315,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -320,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -325,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -330,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -335,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -340,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -345,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -350,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -355,0,90));
			Instantiate(shot, this.transform.position, new Quaternion(0, -360,0,90));
			yo.GetComponent<Done_PlayerController>().shotAmount+=144;

			Instantiate(explosion, transform.position, transform.rotation);
			yo.GetComponent<Done_PlayerController>().onScreen=false;
			Destroy(gameObject);
		}
		}



	
	}
}
